### ISSUE TITLE
Study Quantum kernel

### ISSUE THREAD

**Issue by mickahell** [Travis-S-IBM/q-kernel-ops#4]
Copy form https://github.com/Travis-S-IBM/q-kernel-ops/issues/3#issuecomment-1067215056

---

Cross-posting from Slack & expanding.

To build up a quantum kernel matrix, we're going to need to use some parameterized quantum circuits (PQCs).
A good way to do this is using the [Qiskit Circuit Library](https://qiskit.org/documentation/apidoc/circuit_library.html), especially the [`TwoLocal` circuit](https://qiskit.org/documentation/stubs/qiskit.circuit.library.TwoLocal.html#qiskit.circuit.library.TwoLocal)

In our study, we used a variety of circuits from [this paper](https://arxiv.org/abs/1905.10876) ("Sim et al.). For this work, we don't have to do that. I would suggest the following circuits from the SIm et al. paper (see Figure 2):
* One of circuits 2, 3, or 4
* One of circuits 5, 6, 13, or 14
* One of circuits 9 or 10
* One of circuit 18 or 19

We can pick a modest number of qubits (e.g., 2-10) or so. There's no reason, AFAIK, to go crazy with this.
In addition, in terms of the number of "layers" (terminology from Sim et al.) or "reps" (in `TwoLocal` documentation), we could fix that to be 1 for simplicity and then expand if we think that's an interesting direction to go.

Because we have to insert ("bind") parameters to these circuits, it's also crucial for reproducibility purposes that we fix the seed of whatever random number generator we are using.

With respect to generating the matrices themselves, I suggest first generating data files containing each kernel matrix element as its own row, with corresponding metadata. For starters, I suggest doing ideal (statevector) simulation; the data files would look something like this: suppose we are doing simulations of circuit ID `id`. The data file could be called `kernels-[id]-ideal.csv`, and would contain the following:

| width | layers | shots | seed1 | seed2 | fidelity of result |
| --- | --- | --- | --- | --- | --- |

where `seed1` and `seed2` are the seed values used to generate the parameter bindings for the circuit used to calculate the kernel. And the result should always be an all 0 bitstring.

NOTE: We found it necessary to use a different file format, [feather](https://www.journaldev.com/53105/feather-file-format-in-python), which we found necessary to facilitate storage of the data files.

Notice that `seed1` and `seed2` would range over values 1, 2, ...., D, meaning that the largest kernel matrix we could extract from this data is DxD. I think we got up to D=1000 and then realized it just took too long to generate more data.

Using this data, we can then mock up different realizations of quantum kernel matrices by sampling from this data set. In particular, if `seed1` and `seed2` range from 1,2,... , D, then to generate an _s x s_ kernel matrix, we can randomly sample a choice of integers of size _s_, and then subsample the data file to values of `seed1` and `seed2` in that choice.

--- 

### Todo
- [x] Generate the array and tell what we got
- [x] One of circuits 2, 3, or 4
- [x] One of circuits 5, 6, 13, or 14
- [x] One of circuits 9 or 10
- [x] One of circuit 18 or 19
- [x] Runtime sampler program
- [x] Gen files program
- [x] Compatible with Actions
- [x] Kernel circuit program

EPIC #5
